# Generated by Django 5.2.5 on 2025-08-22 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default='', editable=False, max_length=12, unique=True)),
                ('user_type', models.CharField(choices=[('volunteer', 'Gönüllü'), ('scholar', 'Bursiyer'), ('staff', 'Personel')], max_length=20)),
                ('full_name', models.CharField(max_length=120)),
                ('tc_no', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('transport', models.CharField(choices=[('bus', 'Otobüs'), ('plane', 'Uçak')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('ticketed', 'Bilet Alındı')], default='pending', max_length=20)),
                ('pnr_code', models.CharField(blank=True, max_length=40, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='tickets.ticketrequest')),
            ],
        ),
    ]
