# Generated by Django 5.2.5 on 2025-08-22 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketrequest',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='purchased_by',
            field=models.ForeignKey(blank=True, help_text='Bileti alan personel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_purchased', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='tracking_code',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AddIndex(
            model_name='ticketrequest',
            index=models.Index(fields=['tracking_code'], name='tickets_tic_trackin_4bde8f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketrequest',
            index=models.Index(fields=['status'], name='tickets_tic_status_96eb76_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketrequest',
            index=models.Index(fields=['transport'], name='tickets_tic_transpo_820558_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketrequest',
            index=models.Index(fields=['user_type'], name='tickets_tic_user_ty_b3c097_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketrequest',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_afca80_idx'),
        ),
    ]
