# Generated by Django 5.2.5 on 2025-08-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_changerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('ticketed', 'Bilet Alındı'), ('rejected', 'Bilet Reddedildi')], default='pending', max_length=20),
        ),
    ]
