# Generated by Django 5.2.5 on 2025-08-22 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='preferred_airline',
            field=models.CharField(blank=True, choices=[('THY', 'THY'), ('PEGASUS', 'Pegasus'), ('AJET', 'AJet')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='reason',
            field=models.CharField(choices=[('teknofest', 'TEKNOFEST'), ('gorevlendirme', 'Görevlendirme'), ('diger', 'Diğer')], default='teknofest', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='reason_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='return_destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ticketrequest',
            index=models.Index(fields=['reason'], name='tickets_tic_reason_0267e7_idx'),
        ),
    ]
