# Generated by Django 5.2.5 on 2025-08-22 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketrequest_departure_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Kaydı reddeden personel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='preferred_airline',
            field=models.CharField(blank=True, choices=[('THY', 'THY'), ('AJET', 'AJet'), ('PEGASUS', 'Pegasus')], max_length=20, null=True),
        ),
    ]
