# Generated by Django 5.2.5 on 2025-09-03 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticketrequest_rejected_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('user_type', 'Kullanıcı Türü'), ('transport', 'Ulaşım Türü'), ('reason', 'Talep Nedeni'), ('airline', 'Havayolu')], max_length=50)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='trip_type',
            field=models.CharField(choices=[('oneway', 'Tek yön'), ('roundtrip', 'Gidiş - Dönüş')], default='oneway', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{2}-\\d{2}$', 'Telefon formatı 5xx-xxx-xx-xx olmalı.')]),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='preferred_airline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='reason',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Kaydı reddeden personel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='tc_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, 'TC Kimlik numarası 11 haneli olmalı.'), django.core.validators.RegexValidator('^\\d{11}$', 'TC Kimlik numarası sadece rakamlardan oluşmalı.')]),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='transport',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='user_type',
            field=models.CharField(max_length=50),
        ),
    ]
